repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.1
  hooks:
    - id: ruff-check
    - id: ruff-format
- repo: https://github.com/PyCQA/bandit
  rev: '1.7.7'
  hooks:
    - id: bandit
      args: ["-r", "src/", "-ll", "-ii"]
      pass_filenames: false 
      stages: [pre-push]
- repo: local
  hooks:
    - id: requirements
      name: Update requirements.txt
      entry: bash -c "cd ./backend && uv export --no-annotate --no-header --format requirements.txt > ./requirements.txt"
      language: system
      files: './uv\.lock$'
      pass_filenames: false      
      stages: [pre-commit]
    - id: pytest
      name: run tests with pytest
      entry: uv run pytest -s -v
      language: system
      pass_filenames: false
      stages: [pre-push]