name: Backend CI

on: [push]

defaults:
  run:
    working-directory: ./backend

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install UV and Dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv .venv
          uv sync --all-groups
      - name: Run Pytest
        run: uv run pytest . -s -v --cov -cov-fail-under=80
        env:
        # dummy database credentials to run the tests.
          DB_DIALECT: "postgresql"
          DB_DRIVER: "postgre_generic_driver"
          DB_USERNAME: "UserTest"
          DB_PASSWORD: "PasswordTest"
          DB_HOST: "0.0.0.0"
          DB_PORT: "5432"
          DB_NAME: "SomeTestDatabase"

  linter:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install UV and Dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv .venv
          uv sync --all-groups
      - name: Run Ruff
        run: uv run ruff check .

  security:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install UV and Dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv .venv
          uv sync --all-groups
      - name: run Bandit
        run: uv run bandit -r src/